#+hugo_base_dir: ~/Documentos/ryojin_desu

* Alfonso I
:properties:
:export_file_name: alfonso_p01.org
:export_date: 2026-05-29
:end:

Era Alfonso el hijo más pequeño de un esclavo.
Y como su padre esclavo, Alfonso era miserable; aunque tan solo era un niño pequeño.
Desnudo y sucio andaba por el mundo, caminado sin camino; como sin luz en el entendimiento y neblina en la visión.

Un día Alfonso fue llamado a la presencia del Señor de la casa donde trabajaba toda su familia.
Con alegría se acerco, pero también con mucho miedo, ya nunca había visto al Señor de la casa, ni escuchado su voz.

El Señor se acerco a Alfonso, lo vio temblando y tuvo misericordia de él: le regalo una moneda, brillante como el Sol.
Al verla el niño sintió una alegría que estallaba en colores dentro de su corazón.
Corrió y grito contento, sin saber que al frente de la moneda, una inscripción decía:

#+begin_verse
/¿No clama la sabiduría,
Y alza su voz la inteligencia?
En las alturas junto al camino,
En  el entrada de la ciudad, da voces:
Oh hombres, a vosotros clamo;
Recibid mi enseñanza, y no plata;
Y ciencia antes que oro./
#+end_verse

El niño miro las letras, pero resultaron un misterio para él, pues en su miseria no podía leer.
Aun así tuvo la moneda como tesoro y la guardo.

Ya estando en su triste habitación, miraba las letras doradas en la moneda, angustiado por la idea de si algún día podría entender el significado.
Le preguntaba a su padre y hermanos, pero ellos tampoco entendían la inscripción.
Tal era la curiosidad del niño que pidió a su Padre le permitiera ir a la escuela para aprender con los demás niños a leer y así lograr descifrar el misterio.

Al otro día, los padres de Alfonso lo llevaron a la escuela.
Juntaron un poco de dinero para poder vestirle y no sintiera la avergüenza de su miseria.
A pesar del esfuerzo, los demás estudiantes de la escuela se burlaron de Alfonso al ver la pobreza de su vida.

Andrajoso y con mal olor iba todos los días a la escuela Alfonso.
Un pedazo de pan y unas hojas en una bolsa era todo lo que llevaba.
Por la mañana su madre lo acompañaba en el camino, juntos iban repasando las lecciones del día anterior.

Sin importar la situación tan adversa, Alfonso iba determinado todos los días a la escuela a aprender a leer, pues cada día aumentaba su ilusión de
poder entender la inscripción de la moneda.
Al llegar a su casa, miraba la moneda maravillado; pensando que aquella inscripción debía decir algo hermoso, pues sus padres le habían mencionado que el Señor
de la casa era un hombre muy generoso.

Un día emocionado llevo su preciosa moneda a la escuela para mostrarla a sus compañeros de clase.
Al verla, algunos de ellos comentaron que la moneda debía ser falsa y otros acusaron a Alfonso de ser un ladrón.
Ambos tomaban como base de su juicio la visible pobreza de Alfonso, argumentando que alguien tan miserable no podía poseer un tesoro así sin haberlo robado o falsificado.
Alfonso en su interior se preguntaba si el señor de la casa no le habría puesto una trampa para burlarse de él.
El niño humillado regreso a su casa llorando y escondió su moneda en el rincón más oscuro de su habitación y decidió no mostrarla nunca más.

Paso el tiempo y Alfonso empezó a estar confundido.
A veces se preguntaba si la moneda realmente era verdadera o si el misterio de la inscripción realmente valía la pena.
Siguió yendo a la escuela por mera costumbre, sin ningún anhelo real que motivara su estudio.

Como ya era un poco mayor, su madre dejo de acompañarlo en el camino a la escuela, pero pronto empezó a hacer amigos que caminaban juntos al colegio.
Varios de sus nuevos amigos eran ya más grandes que él y hablaban con mucha pasión sobre temas que Alfonso desconocía.
Así fueron enseñándolo a vestir y a ocultar su pobreza para que nadie la viera.
Y es que Alfonso pronto descubrió que todos ellos eran hijos de esclavos también y que vivían en la misma miseria; mas a simple vista era imposible saberlo.

También sus amigos lo enseñaron a hablar con la simpatía y prudencia particulares de la sociedad; claves del éxito en las relaciones de este mundo.
Le enseñaron a distinguir todo lo que era bello, y a invertir su tiempo en aquellas cosas que verdaderamente eran divertidas e importantes.
Al pasar el tiempo, Alfonso aprendió a enmascarar su miseria y ocultar su pestilente olor; hasta que nadie podía reconocer que provenía de una familia de esclavos.

Un día, después de salir de la escuela; sus amigos llevaron a Alfonso de visita a casa de Don Abundio, un hombre muy rico que vivía en las afueras de la ciudad.
