#+HUGO_BASE_DIR: ~/Documentos/ryojin_desu

* Alfonso II
:properties:
:export_file_name: alfonso_p02.org
:export_date: 2026-10-03
:end:

/Como aves que se apresuran a las redes, así caminaban aquellos jóvenes, sin saber que iban contra su vida; así caminaban hasta que las saetas del cazador traspasaron su corazón./

En la casa de Don Abundio las presas eran muchas: todas ellas ciegas, necias o adormecidas.
Era una casa con muchas habitaciones, donde la luz del día nunca penetraba y sin embargo; parece que nadie anda a oscuras.
Y por todas partes se puede oír música, conversaciones y risas; hay comida deliciosa y bebida.
Aun desde muy lejos de la casa se percibe la alegría: /las redes ya están tendidas, las aves pronto caerán y perderán sus alas./

Ahí de pie frente a todo el estallido de fiesta se encontraba el pequeño Alfonso lleno de emoción y con algo de miedo.
Por un lado, por su  mente circulaba; al haber vivido en tanta miseria, por fin la suerte le sonreía y podía gozar la vida.
Al mismo tiempo, el miedo se lograba ver en su rostro, al nunca haberse alejado tanto de la casa de sus padres y tardarse en regresar de la escuela.
Don Abundio percibiendo las inquietudes de Alfonso, se acercó para charlar con él y tranquilizarlo.
Con un tono suave, pero serio, y una ligera sonrisa en el rostro; Don Abundio explicó a Alfonso porqué era adecuado entrar a aquel lugar.
Y así, /con la suavidad de sus palabras y la salmearía de sus labios; con va el buey al degolladero/, atrapó Don Abundio a aquel joven.

Alfonso corrió y rió como nunca en su vida, hasta que se hizo de noche y tuvo que volver a casa.

Día otro día, saliendo de la escuela, todos los jóvenes repetían la visita.
Alfonso salía de aquel lugar cada vez más tarde, hasta empezar a regresar a su casa en la madrugada.
Llegaba cansado, pero extasiado de toda la diversión; cerraba sus ojos y no lograba dormir pues los colores y olores de la casa de Don Abundio estaban presentes.
Desvelado, iba a la escuela por la mañana, sin poner nada de atención a lo que le decían.
Solo se sentaba en la banca más lejana a la entrada, recargaba su cabeza sobre la paleta de la silla y dormía, al mismo tiempo que balbuceaba tonterías.
A sus compañeros los hacia reír con sus ocurrencias, mas su familia y maestros no entendían su actitud.
Cuando terminaba el colegio, Alfonso volvía a la vida y ponía toda su energía para ir a la casa de Don Abundio.

Pasaron algunos meses y Alfonso empezó a sentirse un poco aburrido en aquella casa.
Los juegos siempre lo mismo, las conversaciones eran las mismas, las mismas risas; siempre llegaba a la media noche a su casa y no conseguía dormir.
Días después, comenzó a notar que al regresar de la fiesta, llega a su casa con hambre.

Don Abundio rápidamente percibió la pérdida de interés de Alfonso y otros jóvenes; y pronto confeccionó una solución al dilema.
Durante años, había mantenido su casa llena y sabia perfectamente como mantener a todos entretenidos.
Ese mismo día al llegar los jóvenes de la escuela, Don Abundio subió con ellos por la escalera al segundo piso de la casa.

/Como aves presurosas a las redes, van aquellos jóvenes, sin saber, ni entender; así caminaban hasta que las saetas traspasan su corazón./

En el segundo pisa, aquella casa se volvía más oscura.
Y lo que antes eran juegos de niños, ahora era maldad disfrazada en diversión.
Entre las sombras aquellos jóvenes pierden la cordura y el juicio; la inocencia se vuelve un vago recuerdo.
Así, con cada risa, se van volviendo esclavos; y cuando abren los ojos, ya son prisioneros de todo aquello que practicaron.
¿Cómo podrán escapar del lazo del cazador?

Alfonso subía todos los días al segundo piso, al principio con cierta satisfacción.
Pero pronto empezó a notar que el olor repugnante que con tanto trabajo había ocultado, después de ocho horas de fiesta, volvía.
Y volvía más desagradable, pues ahora era el olor de su miseria, la borrachera y el tabaco.
Así regresaba a su casa fastidiado del repugnante aroma; con sus ropas sucias, mucho sueño y sin poder dormir; y también con mucha hambre, pues durante todo el día no había probado
bocado al estar ocupado en la diversión.

Una noche regresando a su casa, cruzó por su mente un pensamiento.
Era la primera vez en mucho tiempo que algo así sucedía, pero por un instante notó que no era feliz.
Venia embriagado de alcohol, caminando dando tumbos por la calle.
Al llegar a su pobre casa se derrumbó en el suelo y entre llanto y vómito quedó dormido por unos treinta minutos.
Pasado este tiempo, lo despertó el asqueroso olor que provenía de su boca.

Estando en el suelo, abrió los ojos y estiró su mano.
Debajo de su cama sacó su preciosa moneda y la miró ilusionado.
Una sonrisa se dibujó en cara, pero luego se ocultó de nuevo en la tristeza al recordar que no podía leerla.
Sin embargo, el destello de aquellas letras doradas era tan grande que quedaron grabadas en su imaginación.

Ahí en el suelo, en la más grande de la miseria, Alfonso repasaba la silueta de cada una de las letras de la moneda.
Y entonces descubrió que podía entender un poco las primeras palabras de la inscripción: ¿no clama la sabiduría?
Alfonso no conocía quién era esa mujer llamada Sabiduría, pero le pareció curioso el nombre.
Pensó en esto un par de segundos y volvió a dormir.
