#+HUGO_BASE_DIR: ~/Documentos/ryojin_desu

* Alfonso II
:properties:
:export_file_name: alfonso_p02.org
:export_date: 2026-08-22
:end:

/Como aves que se apresuran a las redes, así caminaban aquellos jóvenes, sin saber que van contra su vida; así caminaban hasta que las saetas del cazador traspasaron su corazón./
Y en la casa de Don Abundio las presas eran muchas: todas ellas ciegas, necias o adormecidas.
Era una casa llena de habitaciones, donde la luz del día nunca penetra; y sin embargo parece que nadie anda a oscuras.
Y por todas partes se escucha música, conversaciones y risas; hay comida deliciosa y bebida.
Aun desde muy lejos de la casa se percibe la alegría; /las redes ya están tendidas, las aves pronto caerán y perderán sus alas./

Ahí de pie frente a todo el estallido de fiesta se encontraba el pequeño Alfonso y no podía ocultar su felicidad.
Sentía, que al haber vivido en tanta miseria, por fin la suerte le sonreía y podía gozar de su vida.

Don Abundio se acercó a él y platicaron.
Fue una platica formidable, pues Don Abundio era un hombre con una personalidad fascinante que sabia hacer reír a todos.
Alfonso comió, corrió y rió como nunca en su vida; hasta que se hizo de noche y tuvo que volver a casa.

Al otro día, saliendo de la escuela, repitieron todos los jóvenes la visita.
eEn casa de Don Abundio siempre había comida; siempre había bebidas, música, baile, juegos para todos.
En algunos cuartos había pantallas inmensas, donde se podía ver películas o jugar a los más modernos videojuegos.

Alfonso salía de aquel lugar cada vez más tarde, hasta empezar a regresar a su casa en la madrugada.
Llegaba cansado, pero extasiado de toda la diversión; cerraba sus ojos y no lograba dormir pues los colores y olores de la casa de Don Abundio estaban presentes.

Desvelado, iba a la escuela por la mañana, sin poner nada de atención a lo que le decían.
Solo se sentaba en la banca más lejana a la entrada y al profesor, recargaba su cabeza sobre la paleta de la silla y hacia como que dormía, al mismo tiempo que balbuceaba tonterías.
A sus amigos los mataba de la risa con sus ocurrencias, aunque los profesores lo ignoraban, pues consideraban era un caso perdido. Cuando terminaba el colegio,
Alfonso volvía a la vida y ponía toda su energía en las actividades en la casa de Don Abundio.

Pasaron algunos meses y Alfonso empezó a notar que bajada de intensidad su experiencia en la mansión.
La comida empezaba a aburrirlo y los juegos siempre eran similares: las conversaciones eran las mismas, las mismas risas. Siempre llegaba a la media noche a su casa y no conseguía dormir.
Unos días después comenzó a notar que al regresar de las fiestas, se quedaba con hambre.

Don Abundio rápidamente percibió la pérdida de interés de Alfonso y otros jóvenes en la fiesta y decidió solucionar el problema.
Durante años, había mantenido ese lugar lleno de personas y sabia perfectamente como mantenerlas entretenidas, sin que en ningún momento dejaran de ser felices.
Ese mismo día al llegar los jóvenes de la escuela, Don Abundio subió con ellos por la escalera al segundo piso de la casa.

En el segundo piso había otro tipo de diversiones, diseñadas para todos aquellos jóvenes que ya no querían divertirse como infantes.
Entre los asistentes de la fiesta circulaba la cerveza y el tabaco, la música era más estruendosa y sensual; las pantallas más brillantes y con películas más emocionantes.
Los videojuegos más realistas. En resumen: una experiencia enriquecida.

Alfonso empezó a subir todos los días al segundo piso de la mansión y al principio le agrado.
Pero pronto empezó a notar que el olor repugnante que con tanto trabajo había ocultado, después de ocho horas de fiesta, volvía.
Y volvía más desagradable, pues ahora era el olor de su miseria, la borrachera, y el tabaco.
Así regresaba a su casa fastidiado del repugnante aroma; con sus ropas sucias, mucho sueño y sin poder dormir; y también con mucha hambre, pues durante todo el día no había probado
bocado al estar ocupado en la diversión.

Una noche regresando a su casa, cruzó por su mente un pensamiento.
Era la primera vez en mucho tiempo que algo así sucedía, pero por un instante notó que no era feliz.
Venia embriagado de alcohol, caminando dando tumbos por la calle.
Al llegar a su pobre casa se derrumbó en el suelo y entre llanto y vómito quedó dormido por unos treinta minutos.
Pasado este tiempo, lo despertó el asqueroso olor que provenía de su boca.

Estando en el suelo, abrió los ojos y estiró su mano.
Debajo de su cama sacó su preciosa moneda y la miró ilusionado.
Una sonrisa se dibujó en cara, pero luego se ocultó de nuevo en la tristeza al recordar que no podía leerla.
Sin embargo, el destello de aquellas letras doradas era tan grande que quedaron grabadas en su imaginación.

Ahí en el suelo, en la más grande de la miseria, Alfonso repasaba la silueta de cada una de las letras de la moneda.
Y entonces descubrió que podía entender un poco las primeras palabras de la inscripción: ¿no clama la sabiduría?
Alfonso no conocía quién era esa mujer llamada Sabiduría, pero le pareció curioso el nombre.
Pensó en esto un par de segundos y volvió a dormir.
