#+hugo_base_dir: ~/Documentos/ryojin_desu

* All traditions are bound to die
:properties:
:export_file_name: all_traditions_are_bound
:export_date: 2024-05-08
:end:

Recientemente platicando con un amigo de Bolivia llegamos a la conclusion de que todas las tradiciones están condenadas a morir.
Para poner un poco de contexto, mi amigo estaba preocupado porque, al regresar a su pueblo, había notado con horror que los jóvenes encargados del pastoreo
ahora se entretienen viendo vídeos y escuchando música mientras el rebaño pasta.
En el pasado, de acuerdo con mi amigo, la misma actividad implicaba hacer mucha más actividad física y relaciones sociales.

La preocupación de mi amigo debe entenderse más allá de los efectos en la salud mental y física de los jóvenes pastores.
Es una preocupación más primordial; basada en el miedo de ver morir un legado, en ver morir aquellas tradiciones que durante muchas generaciones la gente de su pueblo ha preservado.

Los humanos tendemos a poner valor a nuestras tradiciones porque las vemos como un logro; una muestra de nuestra esencia y valores que se transmite a través del tiempo.
Y no solo ponemos valor a ellas, sino que también estamos orgullos de ellas, al grado que se llegan a convertir en la personificación de un pueblo.

No obstante, todas las tradiciones están condenadas a morir.
No digo esto porque de alguna manera este exento de las mismas, o sienta alguna superioridad moral sobre las personas que guardan con recelo sus tradiciones.
Mi argumento trata de estar basado en la evidente aunque incómoda realidad del carácter transitorio de la vida y la esencia de la vida humana.
Luego entonces, nuestras tradiciones al ser producto de seres finitos son también finitas y variantes en el tiempo.

Hasta ahora creo que nada de lo que escribo es sobresaliente.

Hace unos años, la época decembrina me generaba las mismas sospechas por estar llena de tradiciones.
En mi ignorancia cuestioné una fiesta (la Navidad), que bajo mi perspectiva tenia las mismas características que las demás fiestas nacionales.

Es cierto que junto a la celebración del nacimiento de Jesucristo se han incorporado tradiciones humanas, tal vez llenas de buenas intenciones y que provocan lindos recuerdos;
pero sin ningún valor trascendente.
Luego entonces no veo problema en ver morir con el tiempo a los Santa Clauses y reyes magos; así como los arboles y regalos o las posadas.

A pesar de esto, la celebración de la Navidad en la iglesia cristiana ha perdurado, aun cuando ha conectado con distintos pueblos y costumbres a través de los siglos.
La razón de su resistencia yace en su origen histórico y sobrenatural.
Aclaro, no existe ningún argumento bíblico explícito que nos obligue como cristianos a celebrar el nacimiento de nuestro Señor.
No hay mandamientos (aunque tampoco prohibiciones), ni tampoco existe una forma incuestionable de establecer la fecha exacta del nacimiento de Cristo Jesús.

Lo de histórico y sobrenatural lo digo por las siguientes dos piezas de evidencia: el nacimiento de Cristo es un hecho histórico (registrado por historiadores) y sobrenatural
porque se encuentra revelado en la biblia.
A continuación profundizare en el segundo punto, ya que el primero me parece claro.

Los cristianos creemos en la veracidad de la Biblia, la creemos como la única fuente inspirada por Dios para guiar nuestras vidas.
Luego entonces, si el nacimiento del mesías está registrado en ella, no importa que tengamos dificultades para datar su fecha o que la fecha que proponemos se cruce (supuestamente)
con otras celebraciones.
Es la convicción de que Cristo nació la que celebramos.

Y esa certeza ha inspirado a cristianos durante siglos a celebrar el nacimiento. En una misma fe y como un solo cuerpo declaramos creer en su venida y en su obra redentora.
Aunque la iglesia no es la máxima autoridad; la iglesia actuando conforme a lo que revela la palabra establece un argumento contundente.

Por decirlo en otras palabras, no es solo el hecho histórico del nacimiento (aunque hay certeza en ello) o en la existencia del cordero de Dios
(que es más real que todo lo que esta a nuestro alrededor).
Es la convicción de que lo que celebramos está relevado por Dios, y su palabra no puede estar equivocada.

En la familia de mis padres hace muchos años dejamos de celebrar la Navidad por nuestra falta de firmeza.
En su lugar celebramos /a la familia/ para tratar de sostener las tradiciones familiares.
Sin embargo, aunque me duele escribirlo, mis padres, mis hermanos y yo moriremos con nuestras tradiciones en algún futuro no muy lejano.
No a si la Navidad.
