#+HUGO_BASE_DIR: ~/Documentos/ryojin_desu

* Fire at the Diet of Worms
:PROPERTIES:
:EXPORT_FILE_NAME: fire_at_the_diet
:EXPORT_DATE: 2025-08-11
:END:


Estar /consciente/ o ser /conciente/ son dos cosas diferentes. Por un lado, la consciencia con /sc/ representa el acto de estar despierto, estar vivo; de pensar.
Es la condición humana en la que percibimos el mundo a través de nuestros sentidos y opinamos acerca de los estímulos que recibimos.
Aclaro, esta definición no es académica, pero creo que es clara.

La conciencia (quitando la /s/) es un estado superior. No solo involucra la recepción de estímulos y la expresión de nuestros pensamientos, sino que requiere establecer juicios sobre ellos.
En mi opinion, el acto más puro y elevado de la conciencia humana es la conciencia moral: nuestra capacidad de discernir entre el bien y el mal.
Tal vez muchos Psicólogos y filósofos no estén de acuerdo con esta opinión, sin embargo, prefiero no hacerles caso.

La conciencia humana es un fenómeno fascinante y muy complejo de entender. San Agustin de Hipona argumentaba que el origen de ella se encuentra en nuestra memoria más primitiva.
Una memoria antiquísima que nos conecta al jardín del Eden, cuando el creador nos compartió su naturaleza y nosotros la perdimos en nuestra rebeldía.
En esa memoria (como en el BIOS de una computadora), perduran nuestros conocimientos más puros sobre el carácter de Dios y nuestros ideales de justicia, amor y verdad.

El 18 de Abril de 1521, Martin Lutero compadeció ante la Dieta imperial de Worms, haciendo un ejercicio de conciencia.
El motivo de la dieta (del latín día --- diario) era llevar acabo una especie de juicio, en el cual a Lutero tenia la oportunidad de defenderse de los cargos
de hereje y arrepentirse de sus pensamientos (expresados en libros). No obstante de encontrarse rodeado de muchos de los hombres más sabios y poderosos del mundo,
Lutero no se retractó; argumentando que su conciencia estaba cautiva por la palabra de Dios.

Las escrituras son el medio por el cual a Dios le ha placido revelarse a nuestra humanidad (espíritu/mente). En ellas están escritas todas aquellas cosas del carácter
del creador que no podemos inferir de la naturaleza o de nuestra conciencia. Es decir, en ellas está el conocimiento del bien y el mal,
los preceptos morales de Dios, pero también apuntan más allá, a la obra redentora de Cristo Jesus.

Leer  y estudiar la Biblia, para los que hemos nacido de nuevo, es experimentar lo divino en la tierra. Luego entonces,
Lutero había tenido un encuentro real con Dios al buscarlo en las paginas de aquella biblia en Latin.  Su conciencia, que le daba un conocimiento burdo de la bondad de Dios,
había despertado a una nueva realidad y estaba atrapada en la inapagable luz de Jesucristo.
Yendo de vuelta a San Agustin, el Cristiano frente a la palabra vuelve al jardín del Eden para tener comunión real con el Dios trino y conocer su voluntad.
Ahí encontramos la verdadera paz y libertad.

Considerando esto, puedo entender a un Lutero desafiando todo y sin poder cambiar de dirección.

Los hijos de Dios caminamos por este mundo lleno de dolor y sufrimiento. En ocasiones, nuestra vida y acciones son expuestas en frente de todos.
Como en una pequeña dieta imperial, los sabios y entendidos nos convocan para analizar nuestras palabras; muchas veces exigiendo una defensa o incluso una retractación.
Si llegamos a tal asamblea desnudos, sin la escritura en nuestras manos y nuestra mente; la Dieta imperial es la experiencia más aterradora que uno puede vivir.
Sin embargo, si llegas con la conciencia cautiva, hay victoria y vida.

Ayer cuando me convocaron, yo tampoco pude retractarme; mi conciencia estaba cautiva y no es seguro ir contra la conciencia.
