#+hugo_base_dir: ~/Documentos/ryojin_desu

* God gave me everything (a warning)
:properties:
:export_file_name: god_gave_everything
:export_date: 2026-07-09
:end:

Con la llegada del milenio, llegó mi entrada a la preparatoria.
Y con la llegada de la educación preparatoria comenzó la lucha incesante de ideas y argumentos.
Fueron años difíciles, tratando de defender la fe protestante, en medio de una mayoría Cristiana católica.

Pero en una sociedad Mexicana altamente secularizada, el hecho de que exista una mayoría Católica, no implica que ésta sea ortodoxa.
De hecho, durante mi largo paso a través del sistema de educación pública del país llegue a la conclusión de que muchos Católicos en México no creen en nada.
Fue así como mi lucha por defender el protestantismo se convirtió en una lucha por defender la existencia de Dios.

Dado que mi conocimiento de la Palabra de Dios y de la historia de la Iglesia era muy mediocre, mis argumentos de defensa se basaban en las experiencias.
Por supuesto, al ser aún muy joven mis experiencias eran limitadas, por lo tanto debía recurrir a la experiencia donde la encontrara.
Fue así que empecé a poner atención en las opiniones y estilo de vida de figuras de la cultura popular, pues en ellos encontraba evidencia de que mi fe era genuina.
Mi pensamiento era algo así: si Persona X que es muy famosa, querida y respetada cree en la existencia de Dios, eso demuestra la realidad de Dios.
Más aún: si Persona X dice tener una experiencia con Dios, eso apunta a que la fe Cristiana protestante es genuina, pues mis colegas Católicos Mexicanos no hacen ese
tipo de afirmaciones (en este caso no por la secularización de México, sino por razones doctrinales de la Iglesia Católica).

Desde luego este razonamiento es muy pobre, pero era todo a lo que mi cerebro de dieciséis años llegaba.

A inicios del milenio, la mayor influencia que teníamos los jóvenes de mi edad era la industria de la Musica y MTV.
El internet ya estaba ahí, poco a poco descentralizando nuestros gustos musicales, pero la hegemonía aún pertenecía a la gran corporación televisiva.
Era así que todos los días regresaba a casa de le escuela y almorzaba; para luego enchufarme a la televisión, buscando estar actualizado en las tendencias musicales.
Y fue así que descubrí la canción /God gave me everything/ de Mick Jagger.

En medio de mi cruzada contra la ignorancia del mundo, en aquel tiempo solo puse atención al titulo y coro de la canción; los cuales mencionan a Dios y eso era
suficiente para cubrir mi necesidad de certeza.
Evidencia de una vida espiritual muy pobre.

Más allá de esto, la canción presenta un argumento interesante que quiero analizar; ademas es fácil de entender y comprobar.  Lo podemos enunciar de la siguiente manera:

#+begin_verse
/Si todo lo que me propongo lo consigo,
esto se debe a que Dios me permitió conseguirlo.
Luego entonces, si me permite conseguir lo que quiero,
es porque tengo su aprobación./
#+end_verse

Esta manera de ver la fe es tan vieja como el libro de Job y también sitúa nuestra experiencia como la máxima medida de la verdad.
En este caso son las bendiciones o providencia de Dios las que establecen la prueba; llevándonos a suponer la relación éxito/riqueza con la cercanía a Dios
o una abundante experiencia espiritual.
Vista desde la superficie esta idea no es errónea, aunque no lo suficientemente profunda para explicar la verdadera experiencia Cristiana.
Esto se debe a que los Hijos de Dios experimentamos el amor del Padre tanto en la prosperidad de nuestros objetivos (avance de nuestros proyectos personales), como en
el fracaso de los mismos. Es decir, lo hijos de Dios estamos sujetos a la disciplina de Dios; quien no solo sabe lo que anhelamos, sino lo que nos conviene.

Al otro lado del espectro, el impío experimenta solo el juicio divino (aunque para ellos también hay providencia, pero ese es otro tema),
sin conocer nunca el amor, cuidado y disciplina del Señor.
Luego entonces, si no hay disciplina, nadie los detiene en su perversiones, y en apariencia prosperan en sus obras, cuando en realidad van camino a su destrucción.
Es por esta razón que a veces los Cristianos enfrentamos la realidad del /fracaso/, mientras que los que no temen a Dios prosperan.
Simplemente estamos siendo testigos del amor de nuestro Padre, al mismo tiempo que el necio recibe su desprecio.

Durante mi caminar en la vida me he topado con personas que parecen recibir todo lo que sueñan.
Logran pasar sobre todos sus enemigos, sin ellos tener nunca escrúpulos; sin importarles ninguna regla, ni importarles dañar a alguien más.
Manipulan a todos y engañan a todos, pero pareciera que la justicia de Dios nunca los alcanza.
Al ver a esta situación, a veces ha nacido amargura en mi corazón; sin llegar a entender en verdad el amor y misericordia de Dios.
Porque el aparente fracaso en nuestro día a día se debe muchas veces a que conocemos al hijo de Dios y él dirige nuestros pasos:
no de acuerdo a nuestra opinión o deseos, sino con base en su infinita sabiduría.

Regresando al tema de la canción, podemos hacer una advertencia (a Mick Jagger): si crees que Dios te ha todo, pero no has conocido de su hijo, tal vez en tu futuro solo te espera
la vergüenza de encontrarte desnudo delante de él.
Tomando como referencia las palabras de Asaf en el Salmo 73; la prosperidad de los malos solo traen su fin.
Por supuesto, al escribir respecto a este tema, lo hago con un profundo temor de Dios, dado que es algo muy severo hablar de la condenación de alguna persona.
Pero la Fe Cristiana me ha enseñado que la verdad de Dios no solo está en las experiencias vividas, sino en todo aquello que la Palabra de Dios nos revela.
