#+HUGO_BASE_DIR: ~/Documentos/ryojin_desu

* God gave me everything (a warning)
:PROPERTIES:
:EXPORT_FILE_NAME: god_gave_everything
:EXPORT_DATE: 2026-06-27
:END:

Con la llegada del milenio, llegó mi entrada a la preparatoria.
Y con la llegada de la educación preparatoria comenzó la lucha incesante de ideas y argumentos.
Fueron años difíciles, tratando de defender la fe protestante, en medio de una mayoría Cristiana católica.

Pero en una sociedad Mexicana altamente secularizada, el hecho de que exista una mayoría Católica, no implica que ésta sea ortodoxa.
De hecho, durante mi largo paso a través del sistema de educación pública del país llegue a la conclusión de que muchos Católicos en México no creen en nada.
Fue así como mi lucha por defender el protestantismo se convirtió en una lucha por defender la existencia de Dios.

Dado que mi conocimiento de la Palabra de Dios y de la historia de la Iglesia era muy mediocre, mis argumentos de defensa se basaban en las experiencias.
Por supuesto, al ser aún muy joven mis experiencias eran limitadas, por lo tanto debía recurrir a la experiencia donde la encontrara.
Fue así que empecé a poner atención en las opiniones y estilo de vida de figuras de la cultura popular, pues en ellos encontraba evidencia de que mi fe era genuina.
Mi pensamiento era algo así: si Persona X que es muy famosa, querida y respetada cree en la existencia de Dios, eso demuestra la realidad de Dios.
Más aún: si Persona X dice tener una experiencia con Dios, eso apunta a que la fe Cristiana protestante es genuina, pues mis colegas Católicos Mexicanos no hacen ese
tipo de afirmaciones (en este caso no por la secularización de México, sino por razones doctrinales de la Iglesia Católica).

Desde luego este razonamiento es muy pobre, pero era todo a lo que mi cerebro de dieciséis años llegaba.

A inicios del milenio, la mayor influencia que teníamos los jóvenes de mi edad era la industria de la Musica y MTV.
El internet ya estaba ahí, poco a poco descentralizando nuestros gustos musicales, pero la hegemonía aún pertenecía a la gran corporación televisiva.
Era así que todos los días regresaba a casa de le escuela y almorzaba; para luego enchufarme a la televisión, buscando estar actualizado en las tendencias musicales.
Y fue así que descubrí la canción God gave me everything de Mick Jagger.

En medio de mi cruzada contra la ignorancia del mundo, en aquel tiempo solo puse atención al titulo y coro de la canción; los cuales mencionan a Dios y eso me era
suficiente para cubrir mi necesidad de certeza.
Más allá de esto, la canción presentaba un argumento interesante, fácil de entender, comprobar y que se puede enunciar de la siguiente manera:

Si todo lo que me propongo lo consigo, esto se debe a que Dios me permitió conseguirlo.
Luego entonces, si me permite conseguir lo que quiero, es porque tengo su aprobación.
