#+hugo_base_dir: ~/Documentos/ryojin_desu

* Nothing in my hands I bring
:properties:
:export_file_name: nothing_in_hands
:export_date: 2025-10-16
:end:

Traducir un texto de un idioma a otra es una tarea compleja.
A veces la traducción conlleva la pérdida de estructuras gramaticales o a falta de claridad.
A veces esta situación se agrava, poniendo en dos extremos de una balanza la claridad y la calidad de la traducción.

Tratar de traducir una canción es un proceso más difícil.
Esto se debe a que además de buscar claridad y belleza (la gramática es la cualidad estética del lenguaje), debemos buscar mantener el ritmo de una melodía.
Cuando la letra de una canción simplemente refleja el pensamiento/sentimiento de una persona, sacrificar la claridad al traducirla
(para tratar de enfatizar los otros dos factores), no tiene mayor problema.
Cuando tratamos de traducir un himno cristiano, el problema es diferente.

Los himnos están escritos para transmitir un mensaje muy claro, resaltando al mismo tiempo la belleza por medio de la letra y la música.
La letra de un himno también debe transmitir un tono de reverencia, necesario al dirigirnos en la adoración a Dios.
Luego entonces, traducir himnos debe ser una tarea gigantesca.

Hace algunos años leí un sermón de Charles Spurgeon (el príncipe de los pastores) en el que citaba el famoso himno "Rock of ages".
Aunque la cita me pareció muy bella, mi corta experiencia escuchando himnos me impidió identificarla y pase varios años sin encontrar su origen.
Tiempo después descubrí el origen de la cita y escuché el himno en inglés y español.

El himno Roca de la eternidad (titulo en español) fue escrito hace casi 300 años en Inglaterra.
En la letra de este canto se encuentra un resumen muy claro y bello de la salvación, la gracia redentora, y nuestra incapacidad como hombres de alcanzar
este beneficio a través de nuestro medios, si no solo por la fe en Cristo Jesús.

Conectando con lo que mencioné al principio sobre la traducción de himnos, la versión en inglés y español tienen diferencias importantes.
En particular, el texto que cita Spurgeon no se encuentra en la versión en español.
El texto en cuestión es la tercera estrofa del himno (traducida torpemente por mi):

#+begin_verse
/Nada traigo en mis manos;
solo a la cruz me aferro;
tú que estás desnudo, ven a él para que te vista;
tú que estás desesperado, busca en él la gracia;
moribundo, corriendo voy a la fuente;
límpiame oh mi redentor o moriré./
#+end_verse

La razón del porqué la versión en español no contiene la estrofa a mi parecer es teológica, aunque solo especulo.
Y especulo porque hay veces que la gracia de nuestro Dios a nuestros ojos parece tan inmensurable que nuestra humanidad no logra comprenderla en su profundidad;
nos da temor y tratamos de esconderla.

No obstante esta dificultad, la cuarta estrofa del himno en español me parece sublime:

#+begin_verse
/Cuando vaya a responder
en Tu augusto tribunal,
se mi escondedero fiel,
Roca de la eternidad./
#+end_verse

Hace unas semanas murió un miembro de mi familia.
Un hombre que vivió una vida lleno de dolor, pena y vergüenza.
Solo Dios sabe si había fe en su corazón.
Años atrás, una oración de salvación hubiera sido para mi el testimonio certero del estado de su alma.
Ya no lo pienso así.
El escuchar una oración de confesión nos da (un buen) testimonio a los que estamos alrededor, pero la salvación es un asunto privado entre Dios y los hombres:
solo El conoce si hay fe en el corazón.
Mi ruego a Dios es que el haya tocado el corazón de este hombre antes de partir, y que lo haya convencido que sin El no hay vida.
Y que delante de aquel augusto tribunal (como todos algún día estaremos), el pueda esconderse de la ira de Dios, detrás de la Roca de la eternidad:
Jesucristo... para entrar en el reposo eterno.
