#+hugo_base_dir: ~/Documentos/ryojin_desu

* The Unforgiven II
:properties:
:export_file_name: unforgiven_two
:export_date: 2026-08-31
:end:

Tenia veintidós años, cuando un Martes a las $7$ de la mañana entré a un salón de clases en la Universidad Nacional Autónoma de México.
La clase era sobre Costos y evaluación de proyectos (Contaduría), y para un grupo de futuros Ingenieros era la clase más horrible que podíamos llevar.
Ahí en ese salón, se encontraba la mujer que después se convertiría en mi mejor amiga, mi novia y posteriormente mi esposa; aunque para eso aún faltaban un par de años.
En ese momento todavía no nos conocíamos, pero sabíamos de nuestra mutua existencia por conversaciones con otros amigos.

Por esas épocas todos los Domingos por la mañana me despertaba e iba con mis padres, hermanos y sobrinos a la Iglesia que juntos habíamos ayudado a levantar;
aquella que empezó en el estacionamiento de una casa y cuyo pastor era un hombre sin preparación.
Habían pasado ya cerca de tres años desde el comienzo de aquella Iglesia y las enseñanzas de este hombre se había vuelto mas polémicas, dejando atrás los principios básicos
de la vida cristiana, para convertirse en una especie de mezcla entre ocultismo/espiritismo y clases de superación personal.

Joven y torpe a mis veintidós años, yo seguía al pie de la letra las enseñanzas del auto proclamado /Apóstol/, para luego enfrentarme a la cruda realidad de que no servían para nada.
Fui así como pasé varios años desde mi llegada a ese lugar, esperando que mi /intensa/ y /emocionante/ vida espiritual revirtiera los efectos de mi pasada y lasciva adolescencia.
La describo como /intensa/ y /emotiva/, porque esa era su principal característica; ya que no provenía de ningún estudio profundo de la Palabra de Dios, sino solo
sentimientos intensos que llegan un Domingo por la mañana, para después desvanecerse el resto de la semana.
La muy /emotiva/ alabanza me llenaba de /dopamina/, las platicas motivacionales del pastor me sugestionaban para aspirar a  una vida de santidad
(/el secreto para dejar atrás el pecado es esforzarnos mucho para portarnos bien y entonces dejar atrás el pecado/)
y para rematar, la sesión de guerra espiritual/liberación me convencía que todo aquello tenia un trasfondo /místico/ y /elevado/.
En pocas palabras, sellado por la obra del Espíritu Santo: estaba yo muy equivocado.

Así, deprimido después de años de una decadente adolescencia y una moral corrompida; la receta del /Pastor-Apóstol/ para mejorar mi vida fue liberarme de la musica /Rock/,
porque eso era lo que había traído la maldiciones a mi vida.
Llegué ese noche a mi casa y destruí todos mis discos de musica, en una especie de ritual ; en parte conciente de que cuando me depremia
