#+hugo_base_dir: ~/Documentos/ryojin_desu

* A wheel within a wheel
:properties:
:export_file_name: wheel_within
:export_date: 2026-09-29
:end:

El matrimonio está lleno de memorias que se comparten entre dos personas.
Sin embargo, al consultar de manera individual, la exposición de dichas memorias es diferente.
De esta manera, si nos preguntan a mi esposa y a mi sobre nuestros recuerdos, es posible encontrar infinidad de diferencias entre nuestras versiones.
Visto desde afuera, esto pareciera uno de los grandes pecados de vivir en pareja: el no lograr tener una visión uniforme de la realidad que se enfrenta.
No obstante, es mi convicción que dichas diferencias representan una de las más bellas cualidades del matrimonio.
Porque aquello que una sola mente no es capaz de plasmar en letras; el alma de la otra dibuja con colores para describirla.

Durante nuestros primeros años de estudiantes de doctorado, mi esposa y yo comenzamos a tener un mayor interés por estudiar la palabra de Dios.
Al inicio de nuestra relación, ella luchaba mucho con mi falta de interés en las cosas divinas; sin embargo, después de un tiempo de lucha, yo la fui arrastrando
en mi espiral de desanimo y apatía.
Yo escudaba mi desinterés en las experiencias previamente vividas en la /anti-iglesia/, pero en realidad era mi humanidad y maldad la que no me permitían acercarme a Dios.
Fueron años duros para ella, clamando siempre con esperanza por ver una cambio en mi vida.
Gracias a Dios, ese cambio fue sucediendo poco a poco, y durante nuestros estudios doctorales la situación cambio para bien.

Los primeros libros que leímos durante este periodo fueron los dos volúmenes de sermones completos de /Charles Spurgeon/.
Hasta aquí lo que cuento, creo que los dos compartimos la misma visión; pero donde no logramos ponernos de acuerdo es quién nos recomendó leer a /Spurgeon/.
Según ella, fue el Pastor de la iglesia; según yo, fue mi curiosidad por el titulo /El príncipe de los pastores/.
Sin importar quien tenga razón, o si tal vez la verdad sea una mezcla de las dos versiones, leer a /Spurgeon/ fue una de las experiencias más edificantes de nuestra vida.

En las primeras paginas del volumen uno, no muy escondido en aquel denso libro, hay un sermón maravilloso sobre la providencia de Dios.
El texto base de /Spurgeon/ es Ezequiel 1:15-19: el famoso texto de la /rueda en medio de una rueda (wheel within a wheel)/.
A diferencia de algunos pastores modernos que tratan de extraer enseñanzas muy sofisticadas y un poco /místicas/ de este tipo de versículos (Ezequiel es un libro profético),
/Spurgeon/ busca ser claro en su exposición y nunca pierde el objetivo de extraer una enseñanza útil para la iglesia.

Pero entonces, ¿qué tiene que ver la providencia de nuestro Dios con una rueda?

Una analogía que se usa el sermón para establecer el punto de relación entre ambas, es la leyenda de cierto rey que está prisionero y va encadenado en la
carro de guerra de otro rey poderoso.
Mientras las ruedas del carro van girando, el rey aprisionado las mira con cierta alegría, lo cual provoca desconcierte en el otro rey y le pregunta el porqué de su felicidad.
El rey derrotado procede a explicar una de las grandes realidades de la vida: la vida de vueltas, hoy puedes estar en el fondo del abismo, pero mañana puedes levantarte victorioso.
De la misma forma, el éxito que uno goza actualmente, después se puede convertir en miseria.
Luego entonces, el rey derrotado se alegraba pensando que en el futuro encontraría consolación.

Hasta aquí, la explicación de /Spurgeon/ solo apunta a lo que para cualquier persona parece evidente; nuestra vida va girando como las ruedas de aquel carro.
Y si de manera inesperada hoy nuestra vida puede dar un giro hacia el desastre, ¿donde podemos encontrar esperanza?
Es mirando al centro de la rueda, dice /Spurgeon/, ya que en el centro hay un punto que nunca gira, siempre está estable.
Ese punto se asemeja a la providencia divina; el amor de Dios que nunca cambia y se mantiene constante ante todas las circunstancias.
Mientras vamos girando de arriba a abajo, es el amor y paciencia de Dios que siempre está en todas las cosas para guiar a los suyos: sus hijos.
Mientras vamos girando, sus propósitos siempre se cumplen y él nunca se olvida de nosotros.
Nosotros somos parte de esta gigantesca rueda, que no gira de forma caprichosa, sino que al centro de ella Dios la gira por nuestro bienestar.
Así es la providencia divina, donde los hijos de Dios podemos encontrar consuelo y paz.

Años después, casi al final de nuestro doctorado, mi esposa y yo conseguimos una beca para hacer una estancia fuera del país durante tres meses.
Parecía entonces el inicio de un futuro brillante para nosotros, sin saber que la rueda de la vida pronto estaba por girar y mostrarnos su lado más oscuro.
Pronto nos encontraríamos sin dinero, sin trabajo, sin casa y además tendríamos que enfrentar el sorbo /más amargo/ de la vida.
En medio de aquellos momentos de dolor, en mis adentros siempre clamaba porque la rueda diera el siguiente giro; todavía sin llegar a entender por completo
la providencia de Dios y su amor.

Desde entonces, mi esposa y yo nos hemos recuperado y vivido momentos de alegría; para después volver a caer en un giro inesperado, terminando como aquel rey
derrotado arrastrado por un carro de guerra.
Pero hoy en día la esperanza y la sonrisa en nuestro rostro, ya no está simplemente en el hecho de que la rueda dará en algún momento vuelta (porque todas las cosas en esta vida,
aun las aflicciones, tienen una duración finita); sino en que el amor y cuidado de nuestro Padre están siempre al control de ella.
Y nada nos puede separar de él.
